"""Enhanced Markdown report with severity and executive summary."""
from datetime import datetime, timezone

def _severity(text: str) -> str:
    t = str(text).lower()
    if any(w in t for w in ["critical","rce","sqli","vulnerable","exposed"]): return "CRITICAL"
    if any(w in t for w in ["error","misconfig","open port","missing"]): return "HIGH"
    if any(w in t for w in ["warning","deprecated","redirect"]): return "MEDIUM"
    if any(w in t for w in ["info","ok","200","success"]): return "INFO"
    return "NOTE"

def build_report(session, goal, target, results):
    now = datetime.now(timezone.utc).isoformat()
    total = len(results)
    errors = sum(1 for r in results if isinstance(r.get("result"), dict) and "error" in r["result"])
    successes = total - errors
    lines = ["# Kemi-Claw Report", "", "## Executive Summary", f"- **Session:** `{session}`", f"- **Target:** {target}", f"- **Goal:** {goal}", f"- **Generated:** {now}", f"- **Steps:** {total}", f"- **Successful:** {successes}", f"- **Errors:** {errors}", f"- **Success rate:** {int(successes/total*100) if total else 0}%", "", "---", "", "## Detailed Findings", ""]
    for i, r in enumerate(results, 1):
        step = r.get("step", {}) if isinstance(r.get("step"), dict) else {}
        tool = step.get("tool", "unknown"); rationale = step.get("rationale", "(no rationale)")
        result = r.get("result", {})
        lines.append(f"### {i}. `{tool}` — {_severity(str(result))}")
        lines.append(f"*Rationale:* {rationale}"); lines.append("")
        lines.append("**Result:**"); lines.append("```json"); lines.append(str(result)[:2000]); lines.append("```"); lines.append("")
    lines += ["---", "", "## Findings Summary", "", "| # | Tool | Status | Details |", "|---|------|--------|---------|"]
    for i, r in enumerate(results, 1):
        step = r.get("step", {}) if isinstance(r.get("step"), dict) else {}
        tool, result = step.get("tool", "unknown"), r.get("result", {})
        if isinstance(result, dict) and "error" in result: status, detail = "ERROR", str(result["error"])[:80]
        elif isinstance(result, dict) and result.get("status") == 200: status, detail = "OK", f"HTTP {result.get('status')}"
        elif isinstance(result, dict) and result.get("status"): status, detail = str(result.get("status")), ""
        else: status, detail = "DONE", str(result)[:80] if result else "(empty)"
        lines.append(f"| {i} | {tool} | {status} | {detail} |")
    lines += ["", "---", f"*Report generated by Kemi-Claw v4.0 at {now}* "]
    return "\n".join(lines)
