"""Professional pentest report generator — HTML, Markdown, JSON."""
import json, os, time
from datetime import datetime
from .mcp_registry import registry

HTML_REPORT_TEMPLATE = """<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Kemi Security Report</title>
<style>
body{font-family:system-ui,sans-serif;max-width:900px;margin:20px auto;background:#0f172a;color:#e2e8f0;padding:20px}
h1{color:#38bdf8;border-bottom:2px solid #1e293b;padding-bottom:10px}
h2{color:#94a3b8;margin-top:30px}.finding{background:#1e293b;padding:15px;margin:10px 0;border-radius:8px;border-left:4px solid #f59e0b}
.critical{border-left-color:#ef4444}.high{border-left-color:#f97316}.medium{border-left-color:#f59e0b}.low{border-left-color:#22c55e}
.tag{display:inline-block;padding:2px 8px;border-radius:4px;font-size:12px;margin:2px}
.crit-tag{background:#ef4444;color:white}.high-tag{background:#f97316}.med-tag{background:#f59e0b}.low-tag{background:#22c55e}
table{width:100%;border-collapse:collapse;margin:15px 0}th,td{padding:10px;text-align:left;border-bottom:1px solid #1e293b}
th{background:#1e293b;color:#94a3b8}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:20px 0}
.stat{background:#1e293b;padding:20px;text-align:center;border-radius:8px}.stat .num{font-size:2em;font-weight:bold}
</style></head><body>
<h1>🐺 Kemi Security Assessment Report</h1>
<p>Generated: {date} | Target: {target} | Duration: {duration}s</p>

<div class="summary">
<div class="stat"><div class="num">{total}</div>Findings</div>
<div class="stat"><div class="num" style="color:#ef4444">{critical}</div>Critical</div>
<div class="stat"><div class="num" style="color:#f97316">{high}</div>High</div>
<div class="stat"><div class="num" style="color:#f59e0b">{medium}</div>Medium</div>
</div>

<h2>Executive Summary</h2>
<p>{summary}</p>

<h2>Findings</h2>
{findings_html}

<h2>Tools Used</h2>
<table><tr><th>Tool</th><th>Status</th><th>Result</th></tr>
{tools_table}
</table>

<h2>Recommendations</h2>
<ul>{recommendations}</ul>

<p style="margin-top:40px;color:#64748b;text-align:center">
🐺 Generated by Kemi-Claw v6.1 — Autonomous Security Agent<br>
https://github.com/amiraanime500-crypto/kemi-claw-v4
</p></body></html>"""


async def generate_report(target: str, results: list, format: str = "html") -> dict:
    """Generate a professional pentest report from scan results."""
    findings = []
    tools_used = set()
    critical = high = medium = low = 0
    
    for r in results:
        step = r.get("step", {}) if isinstance(r.get("step"), dict) else {}
        res = r.get("result", {}) if isinstance(r.get("result"), dict) else {}
        tool = step.get("tool", "unknown")
        tools_used.add(tool)
        
        severity = "low"
        if isinstance(res, dict):
            if res.get("vulnerable"):
                severity = "critical" if "CRITICAL" in str(res) else "high"
            elif res.get("critical", 0) > 0:
                severity = "critical"
            elif res.get("high", 0) > 0:
                severity = "high"
            elif res.get("medium", 0) > 0:
                severity = "medium"
        
        if severity == "critical": critical += 1
        elif severity == "high": high += 1
        elif severity == "medium": medium += 1
        else: low += 1
        
        findings.append({
            "tool": tool, "severity": severity,
            "detail": str(res)[:500] if isinstance(res, dict) else str(res)[:200],
            "raw": res if isinstance(res, dict) else {"value": str(res)}
        })
    
    # Generate HTML
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    findings_html = ""
    for f in findings:
        sev_class = f["severity"]
        findings_html += f'<div class="finding {sev_class}"><h3><span class="tag {sev_class}-tag">{f["severity"].upper()}</span> {f["tool"]}</h3><pre>{f["detail"]}</pre></div>\n'
    
    tools_table = "".join(f'<tr><td>{t}</td><td>✅</td><td>Executed</td></tr>' for t in sorted(tools_used))
    
    total = len(findings)
    summary = f"A total of {total} finding(s) were identified during this assessment. "
    if critical > 0:
        summary += f"{critical} CRITICAL finding(s) require immediate attention. "
    if high > 0:
        summary += f"{high} HIGH-severity issue(s) were found. "
    summary += "See detailed findings below for remediation guidance."
    
    recommendations = "<li>Apply security patches for all identified vulnerabilities</li>"
    recommendations += "<li>Implement proper input validation and output encoding</li>"
    recommendations += "<li>Enable security headers (CSP, HSTS, X-Frame-Options)</li>"
    recommendations += "<li>Conduct regular security assessments</li>"
    
    html = HTML_REPORT_TEMPLATE.format(
        date=date_str, target=target, duration="N/A",
        total=total, critical=critical, high=high, medium=medium,
        summary=summary, findings_html=findings_html,
        tools_table=tools_table, recommendations=recommendations
    )
    
    return {
        "target": target, "format": format,
        "findings_count": total, "critical": critical, "high": high,
        "medium": medium, "low": low,
        "tools_used": sorted(tools_used),
        "html": html if format == "html" else "",
        "json": {"findings": findings, "summary": {"total": total, "critical": critical, "high": high}}
    }


async def save_report(target: str, results: list, output_path: str, format: str = "html") -> dict:
    """Generate and save report to disk."""
    report = await generate_report(target, results, format)
    
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    content = report.get("html", json.dumps(report.get("json", {}), indent=2))
    with open(output_path, "w") as f:
        f.write(content)
    
    return {
        "saved": True, "path": output_path, "size": len(content),
        "format": format, "findings": report["findings_count"]
    }


registry.register("generate_report", "Generate professional pentest report (HTML/JSON)",
                  {"target": "str", "results": "list", "format": "str"}, generate_report)
registry.register("save_report", "Save generated report to disk",
                  {"target": "str", "results": "list", "output_path": "str", "format": "str"}, save_report)
