"""Email notifications via SMTP with HTML reports."""
import os, smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

SMTP_HOST = os.getenv("SMTP_HOST", "")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASS = os.getenv("SMTP_PASS", "")
SMTP_FROM = os.getenv("SMTP_FROM", "kemi-claw@localhost")
SMTP_TO = os.getenv("SMTP_TO", "").split(",") if os.getenv("SMTP_TO") else []


async def send_email(subject: str, body: str, html: bool = False, to_addr: list = None):
    """Send an email via SMTP."""
    if not SMTP_HOST or not SMTP_USER: return {"email": "SMTP not configured"}
    recipients = to_addr or SMTP_TO
    if not recipients: return {"email": "no recipients"}
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"[Kemi-Claw] {subject}"
        msg["From"] = SMTP_FROM
        msg["To"] = ", ".join(recipients)
        msg.attach(MIMEText(body, "html" if html else "plain", "utf-8"))
        loop = __import__("asyncio").get_event_loop()
        def _send():
            with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=15) as server:
                server.starttls()
                server.login(SMTP_USER, SMTP_PASS)
                server.send_message(msg)
        await loop.run_in_executor(None, _send)
        return {"email": f"sent to {len(recipients)} recipient(s)"}
    except Exception as e: return {"email": f"error: {e}"}


async def send_scan_report_email(session: str, target: str, goal: str, report: str, results_count: int, success_rate: float):
    """Send a full HTML scan report via email."""
    html_body = f"""<html><body style="font-family:Arial;max-width:800px;margin:20px auto">
<h2>🐺 Kemi-Claw v5.0 — Scan Report</h2>
<div style="background:#f8f9fa;padding:15px;border-radius:8px;margin:15px 0">
<p><b>Target:</b> <code>{target}</code></p>
<p><b>Goal:</b> {goal[:200]}</p>
<p><b>Session:</b> <code>{session[:16]}...</code></p>
<p><b>Steps:</b> {results_count} | <b>Success Rate:</b> {int(success_rate)}%</p>
<p><b>Generated:</b> {datetime.utcnow().isoformat()[:19]}</p>
</div>
<h3>Report</h3>
<pre style="background:#f0f0f0;padding:10px;border-radius:5px;white-space:pre-wrap">{report[:3000]}</pre>
<p style="color:#888;font-size:12px">Generated by Kemi-Claw v5.0</p>
</body></html>"""
    subject = f"Scan Complete: {target} — {int(success_rate)}% success"
    return await send_email(subject, html_body, html=True)
